// This is a single line comment

/*
  This is a 
  multi-line comment
*/

console.log("Check the console for comments!");



/*ouput:
PS C:\Users\abdul\OneDrive\Desktop\Jala-Assignments-Abdul-kadir\Frontend\JS> cd js-1
PS C:\Users\abdul\OneDrive\Desktop\Jala-Assignments-Abdul-kadir\Frontend\JS\js-1> node index.js
Check the console for comments!
PS C:\Users\abdul\OneDrive\Desktop\Jala-Assignments-Abdul-kadir\Frontend\JS\js-1> 
 */